// Code generated by "stringer -type=EventID"; DO NOT EDIT.

package event

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[EHistory-0]
	_ = x[EStartChat-1]
	_ = x[EFinishChat-2]
	_ = x[EUserCommit-3]
	_ = x[EChatError-4]
	_ = x[EReset-5]
	_ = x[ERetry-6]
	_ = x[ESystemPrompt-7]
	_ = x[ELoadPrompt-8]
	_ = x[EChatEnable-9]
	_ = x[EError-10]
	_ = x[EAll-11]
}

const _EventID_name = "EHistoryEStartChatEFinishChatEUserCommitEChatErrorEResetERetryESystemPromptELoadPromptEChatEnableEErrorEAll"

var _EventID_index = [...]uint8{0, 8, 18, 29, 40, 50, 56, 62, 75, 86, 97, 103, 107}

func (i EventID) String() string {
	if i < 0 || i >= EventID(len(_EventID_index)-1) {
		return "EventID(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _EventID_name[_EventID_index[i]:_EventID_index[i+1]]
}
